product = [
  {
    name: "The Cat Nice Mug Tee",
    img: "https://m.media-amazon.com/images/I/7176m2hAJyL._AC_SR736,920_.jpg",
    code: "m01",
    brand: "Reebok",
    catagory: "T-shirt",
    price: "29",
    color: "Blue",
    Occasion: "casual",
  },
  {
    name: "Box Nse Long Sleeve Tee",
    img: "https://m.media-amazon.com/images/I/71LsO6LYgCL._AC_SR736,920_.jpg",
    code: "m02",
    brand: "Reebok",
    catagory: "T-shirt",
    price: "34",
    color: "pink",
    Occasion: "casual",
  },
  {
    name: "St. Jean Stripe Sankaty Polo",
    img: "https://m.media-amazon.com/images/I/71GZU3lgE0L._AC_SR736,920_.jpg",
    code: "m03",
    brand: "Vineyard Vines",
    catagory: "T-shirt",
    price: "95",
    color: "pink",
    Occasion: "casual",
  },
  {
    name: "Big & Tall Badge Of Sport ",
    img: "https://m.media-amazon.com/images/I/71nD3hm6pUL._AC_SR736,920_.jpg",
    code: "m04",
    brand: "adidas",
    catagory: "T-shirt",
    price: "29",
    color: "pink",
    Occasion: "casual",
  },
  {
    name: "Short Sleeve Graphic Signature Polo",
    img: "https://m.media-amazon.com/images/I/81gRK3IPGkL._AC_SR736,920_.jpg",
    code: "m05",
    brand: "Vineyard Vines",
    catagory: "T-shirt",
    price: "135",
    color: "blue",
    Occasion: "casual",
  },
  {
    name: "Palan Pique Changeant",
    img: "https://m.media-amazon.com/images/I/81Tktf61H2L._AC_SR480,600_.jpg",
    code: "m06",
    brand: "adidas",
    catagory: "T-shirt",
    price: "155",
    color: "grey",
    Occasion: "casual",
  },
  {
    name: "Halfer Gradient Short Sleeve Tee",
    img: "https://m.media-amazon.com/images/I/81nIY1dZlBL._AC_SR736,920_.jpg",
    code: "m07",
    brand: "Reebok",
    catagory: "T-shirt",
    price: "20",
    color: "black",
    Occasion: "casual",
  },
  {
    name: "Diamond Wood T-Shirt",
    img: "https://m.media-amazon.com/images/I/81448H1gFGL._AC_SR736,920_.jpg",
    code: "m08",
    brand: "Vineyard Vines",
    catagory: "T-shirt",
    price: "26",
    color: "blue",
    Occasion: "casual",
  },
  {
    name: "Deus Ex Machina",
    img: "https://m.media-amazon.com/images/I/71QcsrRvhGL._AC_SR736,920_.jpg",
    code: "m09",
    brand: "Vineyard Vines",
    catagory: "T-shirt",
    price: "39",
    color: "black",
    Occasion: "casual",
  },
  {
    name: "Kahuna Shirt",
    img: "https://m.media-amazon.com/images/I/81RTaEW6dEL._AC_SR736,920_.jpg",
    code: "m10",
    brand: "Vineyard Vines",
    catagory: "shirt",
    price: "94",
    color: "blue",
    Occasion: "party",
  },
  {
    name: "Havana Shirt",
    img: "https://m.media-amazon.com/images/I/811F2IOQxyL._AC_SR736,920_.jpg",
    code: "m11",
    brand: "Reebok",
    catagory: "shirt",
    price: "99",
    color: "blue",
    Occasion: "party",
  },
  {
    name: "Blue Horizon Aztec Print Shirt",
    img: "https://m.media-amazon.com/images/I/81v9FwQwjVL._AC_SR736,920_.jpg",
    code: "m12",
    brand: "adidas",
    catagory: "shirt",
    price: "56",
    color: "blue",
    Occasion: "casual",
  },
  {
    name: "Cotton/Poly Short Sleeve Blue Shirt",
    img: "https://m.media-amazon.com/images/I/710FORNsoaL._AC_SR736,920_.jpg",
    code: "m13",
    brand: "adidas",
    catagory: "shirt",
    price: "39",
    color: "blue",
    Occasion: "outdoor",
  },
  {
    name: "Look Out Short Sleeve Woven Shirt",
    img: "https://m.media-amazon.com/images/I/71xYvfPdnSL._AC_SR736,920_.jpg",
    code: "m14",
    brand: "adidas",
    catagory: "shirt",
    price: "55",
    color: "grey",
    Occasion: "party",
  },
  {
    name: "Slate Ombre Plaid Shirt",
    img: "https://m.media-amazon.com/images/I/81UrXxlVhSL._AC_SR736,920_.jpg",
    code: "m15",
    brand: "Reebok",
    catagory: "shirt",
    price: "52",
    color: "grey",
    Occasion: "outdoor",
  },
  {
    name: "Grey Vintage Foulard Shirt",
    img: "https://m.media-amazon.com/images/I/811W91RAlaL._AC_SR736,920_.jpg",
    code: "m16",
    brand: "Vineyard Vines",
    catagory: "shirt",
    price: "52",
    color: "grey",
    Occasion: "casual",
  },
  {
    name: "Cotton/Poly Short Sleeve Western Shirt",
    img: "https://m.media-amazon.com/images/I/71qY-ejpLDL._AC_SR736,920_.jpg",
    code: "m17",
    brand: "Vineyard Vines",
    catagory: "shirt",
    price: "39",
    color: "grey",
    Occasion: "outdoor",
  },
  {
    name: "The Casablanca Camp Shirt",
    img: "https://m.media-amazon.com/images/I/81fh9wLb8LL._AC_SR736,920_.jpg",
    code: "m18",
    brand: "Vineyard Vines",
    catagory: "shirt",
    price: "78",
    color: "black",
    Occasion: "party",
  },
  {
    name: "Big & Tall Short Sleeve Classic Camper",
    img: "https://m.media-amazon.com/images/I/81h4LM7Z2oL._AC_SR736,920_.jpg",
    code: "m19",
    brand: "Reebok",
    catagory: "shirt",
    price: "54",
    color: "black",
    Occasion: "party",
  },
  {
    name: "Danny Short Sleeve Camp Shirt W706Y2",
    img: "https://m.media-amazon.com/images/I/71if54NQImL._AC_SR736,920_.jpg",
    code: "m20",
    brand: "adidas",
    catagory: "shirt",
    price: "148",
    color: "black",
    Occasion: "outdoor",
  },
  {
    name: "Lay Day Short Sleeve Woven",
    img: "https://m.media-amazon.com/images/I/71UKe-JzPGL._AC_SR736,920_.jpg",
    code: "m21",
    brand: "Vineyard Vines",
    catagory: "shirt",
    price: "59",
    color: "black",
    Occasion: "party",
  },
  {
    name: "Opti-Dri™ Micro-Hex Solid Polo",
    img: "https://m.media-amazon.com/images/I/61bxW+Pp90L._AC_SR736,920_.jpg",
    code: "m22",
    brand: "Reebok",
    catagory: "shirt",
    price: "57",
    color: "pink",
    Occasion: "outdoor",
  },
  {
    name: "Comfort Stretch Chambray Shirt",
    img: "https://m.media-amazon.com/images/I/81JiiTeIbKL._AC_SR736,920_.jpg",
    code: "m23",
    brand: "Vineyard Vines",
    catagory: "shirt",
    price: "59",
    color: "pink",
    Occasion: "casual",
  },
  {
    name: "Seaworthy Long Sleeve Woven Shirt",
    img: "https://m.media-amazon.com/images/I/71-0lLkQPoL._AC_SR736,920_.jpg",
    code: "m24",
    brand: "Vineyard Vines",
    catagory: "shirt",
    price: "188",
    color: "pink",
    Occasion: "outdoor",
  },
  {
    name: "Teal Arrow Print Western Shirt",
    img: "https://m.media-amazon.com/images/I/911hfQT5pnL._AC_SR736,920_.jpg",
    code: "m25",
    brand: "adidas",
    catagory: "shirt",
    price: "53",
    color: "blue",
    Occasion: "casual",
  },
  {
    name: "Crisis 2",
    img: "https://m.media-amazon.com/images/I/71PMzxhkhTL._AC_SR920,736_.jpg",
    code: "m26",
    brand: "Reebok",
    catagory: "shoes",
    price: "59",
    color: "black",
    Occasion: "casual",
  },
  {
    name: "SINGLE SHOE Glycerin 20",
    img: "https://m.media-amazon.com/images/I/71xHVWhlk0L._AC_SR920,736_.jpg",
    code: "m27",
    brand: "adidas",
    catagory: "shoes",
    price: "80",
    color: "black",
    Occasion: "outdoor",
  },
  {
    name: "Alpargata Rover",
    img: "https://m.media-amazon.com/images/I/71zaxozM6TL._AC_SR920,736_.jpg",
    code: "m28",
    brand: "Reebok",
    catagory: "shoes",
    price: "69",
    color: "grey",
    Occasion: "casual",
  },
  {
    name: "Netburner Ballistic FF MT 3",
    img: "https://m.media-amazon.com/images/I/71CsopMKKKL._AC_SR920,736_.jpg",
    code: "m29",
    brand: "adidas",
    catagory: "shoes",
    price: "129",
    color: "black",
    Occasion: "outdoor",
  },
  {
    name: "Generation Zerogrand II",
    img: "https://m.media-amazon.com/images/I/71bBzBDZytL._AC_SR920,736_.jpg",
    code: "m30",
    brand: "adidas",
    catagory: "shoes",
    price: "130",
    color: "grey",
    Occasion: "casual",
  },
  {
    name: "Trackster 200II Knit Sneaker",
    img: "https://m.media-amazon.com/images/I/71x8zMYC5uL._AC_SR920,736_.jpg",
    code: "m31",
    brand: "adidas",
    catagory: "shoes",
    price: "95",
    color: "pink",
    Occasion: "party",
  },
  {
    name: "Classic Slip-On™",
    img: "https://m.media-amazon.com/images/I/715vLwElMnL._AC_SR920,736_.jpg",
    code: "m32",
    brand: "Reebok",
    catagory: "shoes",
    price: "59",
    color: "pink",
    Occasion: "outdoor",
  },
  {
    name: "Cambridge",
    img: "https://m.media-amazon.com/images/I/71-z5m9HV1L._AC_SR920,736_.jpg",
    code: "m33",
    brand: "Reebok",
    catagory: "shoes",
    price: "74",
    color: "blue",
    Occasion: "casual",
  },
  {
    name: "Nova Sneaker Boot",
    img: "https://m.media-amazon.com/images/I/71mu7MqfNZL._AC_SR920,736_.jpg",
    code: "m34",
    brand: "Vineyard Vines",
    catagory: "shoes",
    price: "139",
    color: "blue",
    Occasion: "outdoor",
  },
  {
    name: "Rincon 3",
    img: "https://m.media-amazon.com/images/I/71k3eF4taAL._AC_SR920,736_.jpg",
    code: "m35",
    brand: "adidas",
    catagory: "shoes",
    price: "124",
    color: "blue",
    Occasion: "party",
  },
  {
    name: "Padel 796v3",
    img: "https://m.media-amazon.com/images/I/71o5DaB4PvL._AC_SR920,736_.jpg",
    code: "m36",
    brand: "adidas",
    catagory: "shoes",
    price: "89",
    color: "blue",
    Occasion: "outdoor",
  },
  {
    name: "Authentic™",
    img: "https://m.media-amazon.com/images/I/711eIwcI43L._AC_SR920,736_.jpg",
    code: "m37",
    brand: "Reebok",
    catagory: "shoes",
    price: "59",
    color: "grey",
    Occasion: "party",
  },
];

pro = document.querySelector("div");
product.forEach((element) => {
  let div = document.createElement("div");
  let subdiv = document.createElement("div");
  img = document.createElement("img");
  img["src"] = element.img;
  brand = document.createElement("h2");
  brand.innerText = element.brand;
  pname = document.createElement("p");
  pname.innerText = element.name;
  price = document.createElement("span");
  price.innerText = "$" + element.price;
  cart = document.createElement("button");
  cart.innerText = "Add to Cart";
  subdiv.append(img, cart);
  div.append(subdiv, brand, pname, price);
  document.querySelector(".productcontainer").append(div);
});
